const compatibilityVitains: any = {
    A: {
        B1: 'neutral',
        B2: 'neutral',
        B3: 'neutral',
        B5: 'neutral',
        B6: 'neutral',
        B9: 'neutral',
        B12: 'not compatible',
        C: 'compatible',
        D: 'neutral',
        E: 'compatible',
        K: 'not compatible',
        Fe: 'compatible',
        Mg: 'neutral',
        Cu: 'neutral',
        Ca: 'neutral',
        P: 'neutral',
        Zn: 'compatible',
        Omega3: 'neutral',
    },
    B1: {
        A: 'neutral',
        B2: 'not compatible',
        B3: 'not compatible',
        B5: 'compatible',
        B6: 'not compatible',
        B9: 'neutral',
        B12: 'not compatible',
        C: 'not compatible',
        D: 'neutral',
        E: 'neutral',
        K: 'neutral',
        Fe: 'neutral',
        Mg: 'not compatible',
        Cu: 'neutral',
        Ca: 'not compatible',
        P: 'neutral',
        Zn: 'neutral',
        Omega3: 'neutral',
    },
    B2: {
        A: 'neutral',
        B1: 'not compatible',
        B3: 'compatible',
        B5: 'compatible',
        B6: 'compatible',
        B9: 'compatible',
        B12: 'not compatible',
        C: 'neutral',
        D: 'neutral',
        E: 'neutral',
        K: 'compatible',
        Fe: 'not compatible',
        Mg: 'neutral',
        Cu: 'not compatible',
        Ca: 'neutral',
        P: 'neutral',
        Zn: 'compatible',
        Omega3: 'compatible',
    },
    B3: {
        A: 'neutral',
        B1: 'not compatible',
        B2: 'compatible',
        B5: 'neutral',
        B6: 'compatible',
        B9: 'neutral',
        B12: 'neutral',
        C: 'neutral',
        D: 'neutral',
        E: 'neutral',
        K: 'neutral',
        Fe: 'compatible',
        Mg: 'neutral',
        Cu: 'neutral',
        Ca: 'neutral',
        P: 'neutral',
        Zn: 'neutral',
        Omega3: 'neutral',
    },
    B5: {
        A: 'neutral',
        B1: 'compatible',
        B2: 'compatible',
        B3: 'neutral',
        B6: 'neutral',
        B9: 'compatible',
        B12: 'compatible',
        C: 'compatible',
        D: 'neutral',
        E: 'neutral',
        K: 'neutral',
        Fe: 'neutral',
        Mg: 'neutral',
        Cu: 'not compatible',
        Ca: 'neutral',
        P: 'neutral',
        Zn: 'neutral',
        Omega3: 'neutral',
    },
    B6: {
        A: 'neutral',
        B1: 'not compatible',
        B2: 'compatible',
        B3: 'compatible',
        B5: 'neutral',
        B9: 'neutral',
        B12: 'not compatible',
        C: 'neutral',
        D: 'neutral',
        E: 'neutral',
        K: 'neutral',
        Fe: 'neutral',
        Mg: 'neutral',
        Cu: 'compatible',
        Ca: 'compatible',
        P: 'neutral',
        Zn: 'compatible',
        Omega3: 'compatible',
    },
    B9: {
        A: 'neutral',
        B1: 'neutral',
        B2: 'compatible',
        B3: 'neutral',
        B5: 'compatible',
        B6: 'neutral',
        B12: 'compatible',
        C: 'compatible',
        D: 'neutral',
        E: 'neutral',
        K: 'neutral',
        Fe: 'neutral',
        Mg: 'neutral',
        Cu: 'neutral',
        Ca: 'neutral',
        P: 'neutral',
        Zn: 'not compatible',
        Omega3: 'compatible',
    },
    B12: {
        A: 'not compatible',
        B1: 'not compatible',
        B2: 'not compatible',
        B3: 'neutral',
        B5: 'compatible',
        B6: 'not compatible',
        B9: 'compatible',
        C: 'not compatible',
        D: 'neutral',
        E: 'not compatible',
        K: 'neutral',
        Fe: 'not compatible',
        Mg: 'neutral',
        Cu: 'not compatible',
        Ca: 'compatible',
        P: 'neutral',
        Zn: 'neutral',
        Omega3: 'compatible',
    },
    C: {
        A: 'compatible',
        B1: 'not compatible',
        B2: 'neutral',
        B3: 'neutral',
        B5: 'compatible',
        B6: 'neutral',
        B9: 'compatible',
        B12: 'not compatible',
        D: 'neutral',
        E: 'compatible',
        K: 'neutral',
        Fe: 'compatible',
        Mg: 'neutral',
        Cu: 'not compatible',
        Ca: 'compatible',
        P: 'neutral',
        Zn: 'neutral',
        Omega3: 'compatible',
    },
    D: {
        A: 'neutral',
        B1: 'neutral',
        B2: 'neutral',
        B3: 'neutral',
        B5: 'neutral',
        B6: 'neutral',
        B9: 'neutral',
        B12: 'neutral',
        C: 'neutral',
        E: 'not compatible',
        K: 'neutral',
        Fe: 'neutral',
        Mg: 'neutral',
        Cu: 'neutral',
        Ca: 'compatible',
        P: 'compatible',
        Zn: 'neutral',
        Omega3: 'neutral',
    },
    E: {
        A: 'compatible',
        B1: 'neutral',
        B2: 'neutral',
        B3: 'neutral',
        B5: 'neutral',
        B6: 'neutral',
        B9: 'neutral',
        B12: 'not compatible',
        C: 'compatible',
        D: 'not compatible',
        K: 'not compatible',
        Fe: 'not compatible',
        Mg: 'not compatible',
        Cu: 'not compatible',
        Ca: 'neutral',
        P: 'neutral',
        Zn: 'not compatible',
        Omega3: 'neutral',
    },
    K: {
        A: 'not compatible',
        B1: 'neutral',
        B2: 'compatible',
        B3: 'neutral',
        B5: 'neutral',
        B6: 'neutral',
        B9: 'neutral',
        B12: 'neutral',
        C: 'neutral',
        D: 'neutral',
        E: 'not compatible',
        Fe: 'neutral',
        Mg: 'neutral',
        Cu: 'neutral',
        Ca: 'compatible',
        P: 'neutral',
        Zn: 'neutral',
        Omega3: 'neutral',
    },
    Fe: {
        A: 'compatible',
        B1: 'not compatible',
        B2: 'neutral',
        B3: 'compatible',
        B5: 'neutral',
        B6: 'neutral',
        B9: 'neutral',
        B12: 'not compatible',
        C: 'compatible',
        D: 'neutral',
        E: 'not compatible',
        K: 'neutral',
        Mg: 'not compatible',
        Cu: 'compatible',
        Ca: 'not compatible',
        P: 'neutral',
        Zn: 'not compatible',
        Omega3: 'neutral',
    },
    Mg: {
        A: 'neutral',
        B1: 'not compatible',
        B2: 'neutral',
        B3: 'neutral',
        B5: 'neutral',
        B6: 'neutral',
        B9: 'neutral',
        B12: 'neutral',
        C: 'neutral',
        D: 'neutral',
        E: 'not compatible',
        K: 'neutral',
        Fe: 'not compatible',
        Cu: 'neutral',
        Ca: 'compatible',
        P: 'not compatible',
        Zn: 'neutral',
        Omega3: 'neutral',
    },
    Cu: {
        A: 'neutral',
        B1: 'neutral',
        B2: 'not compatible',
        B3: 'neutral',
        B5: 'not compatible',
        B6: 'compatible',
        B9: 'neutral',
        B12: 'not compatible',
        C: 'not compatible',
        D: 'neutral',
        E: 'not compatible',
        K: 'neutral',
        Fe: 'compatible',
        Mg: 'neutral',
        Ca: 'neutral',
        P: 'neutral',
        Zn: 'not compatible',
        Omega3: 'neutral',
    },
    Ca: {
        A: 'neutral',
        B1: 'not compatible',
        B2: 'neutral',
        B3: 'neutral',
        B5: 'neutral',
        B6: 'compatible',
        B9: 'neutral',
        B12: 'compatible',
        C: 'compatible',
        D: 'compatible',
        E: 'neutral',
        K: 'compatible',
        Fe: 'not compatible',
        Mg: 'compatible',
        Cu: 'neutral',
        P: 'not compatible',
        Zn: 'not compatible',
        Omega3: 'not compatible',
    },
    P: {
        A: 'neutral',
        B1: 'neutral',
        B2: 'neutral',
        B3: 'neutral',
        B5: 'neutral',
        B6: 'neutral',
        B9: 'neutral',
        B12: 'neutral',
        C: 'neutral',
        D: 'compatible',
        E: 'neutral',
        K: 'neutral',
        Fe: 'neutral',
        Mg: 'not compatible',
        Cu: 'neutral',
        Ca: 'not compatible',
        Zn: 'neutral',
        Omega3: 'neutral',
    },
    Zn: {
        A: 'neutral',
        B1: 'neutral',
        B2: 'neutral',
        B3: 'neutral',
        B5: 'neutral',
        B6: 'neutral',
        B9: 'not compatible',
        B12: 'neutral',
        C: 'neutral',
        D: 'neutral',
        E: 'not compatible',
        K: 'neutral',
        Fe: 'not compatible',
        Mg: 'neutral',
        Cu: 'not compatible',
        Ca: 'not compatible',
        P: 'neutral',
        Omega3: 'neutral',
    },
    Omega3: {
        A: 'neutral',
        B1: 'neutral',
        B2: 'compatible',
        B3: 'neutral',
        B5: 'neutral',
        B6: 'compatible',
        B9: 'compatible',
        B12: 'compatible',
        C: 'compatible',
        D: 'neutral',
        E: 'neutral',
        K: 'neutral',
        Fe: 'neutral',
        Mg: 'neutral',
        Cu: 'neutral',
        Ca: 'not compatible',
        P: 'neutral',
        Zn: 'neutral',
    },
}
const compatibilityCheck = (vitamin1: string, vitamin2: string): null | string => {
    if (!vitamin1 || !vitamin2) {
        return null;
    }

    if (vitamin1 === vitamin2) {
        return null;
    }

    const compatibility = compatibilityVitains[vitamin1][vitamin2];

    switch (compatibility) {
        case 'compatible':
            return 'Витамины имеют эффективную совместимсть!';
        case 'neutral':
            return 'Витамины имеют нейтральную совместимсть!';
        case 'not compatible':
            return 'Витамины не совместимы!';

        default:
            throw new Error("Неизвестное значение совместимости");
            ;
    }
}

export default compatibilityCheck;